@include('layouts.app')


<div class="grid sm:grid-cols-3 grid-cols-1 gap-3 bg-[#d8b64b] sm:h-64 lg:h-48 content-center">
    <div class="flex justify-center">
        <img class="w-36 " src="{{asset('storyset/Uploading-amico.png')}}" alt="" >
    </div>
   
    <div > <h1 class=" text-6xl text-white text-center mt-4">Juristify</h1>
        <p class=" text-2xl text-white text-center">Library</p>
    </div>
    <div class="flex justify-center">        

<div data-popover="" id="popover-description" role="tooltip" class="inline-block absolute invisible z-10 w-72 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm opacity-0 transition-opacity duration-300" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 410.4px, 0px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
    <div class="p-3 space-y-2">
        <h3 class="font-semibold text-gray-900 ">Activity growth - Incremental</h3>
        <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
        <h3 class="font-semibold text-gray-900 ">Calculation</h3>
        <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
    </div>
    <div data-popper-arrow="" style="position: absolute; left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
</div>

    </div>
  </div>

<div class="m-2.5 w-full flex justify-center">
    <form  action="{{ route('file.find') }}" method="GET" role="search">
      <div class="max-w-xl">
        <div class="flex space-x-4">
          <div class="flex rounded-md overflow-hidden w-full">
            <input type="text" name="term" class="w-full rounded-md rounded-r-none" />
            <a href="{{route('file.find')}}" >
            <button class="bg-[#374151] text-white px-6 text-lg font-semibold py-4 rounded-r-md">Search</button>
            </a>
          </div>
        </div>
      </div>
    </form>
    <a href={{route('all.uploads')}}>
      <button class="bg-transparent px-6 text-lg font-semibold py-4 rounded-md">Clear</button></a>
  </div>
 {{-- @if (count($files)>=1) --}}
<div class="flex overflow-x-scroll p-10 hide-scroll-bar ">
    <div class="flex flex-nowrap md:ml-20  ">
        <div class="inline-flex px-3 ">
            @foreach ($files as $f)
                @php
                    $cv = explode('/', $f->file);
                    $photo=explode('/',$f->user->img);
                @endphp
                <div>
                    <a href="/storage/dokumentet/{{ $cv[2] }}" download>
                        <div
                            class="w-64 h-64 max-w-xs overflow-hidden rounded-lg shadow-md
hover:shadow-xl transition-shadow duration-300
ease-in-out mx-3.5 flex justify-center items-center">
                            <img class="ml-2" src="{{ asset('/noProfilePhoto/docs.png') }}" width="100px" />
                        </div>
                    </a>
                    <h3 class="block text-center text-lg mx-4  font-bold capitalize max-w-[230px]">{{ $f->title }}</h3>
                    @if ($f->user->img!="public/noProfilePhoto/nofoto.jpg")  
                    <div class="flex p-2 ml-3">
                    <img class="w-10 h-10 rounded-full object-cover"  src="/storage/img/{{$photo[2]}}" alt="Rounded avatar">
                    <p class="capitalize mt-2 ml-1">{{$f->user->name." ".$f->user->surname}}</p>
                    </div>
                    @else
                    <div class="flex p-2 ml-3">
                    <img class="w-10 h-10 rounded-full object-cover" src="{{asset('/noProfilePhoto/'.$photo[2])}}" alt="Rounded avatar">
                    <p class="capitalize mt-2 ml-1">{{$f->user->name." ".$f->user->surname}}</p>
                 </div>
                    @endif
                    <p class="block text-justify mx-4 max-w-[230px]" id="dots{{$f->id}}">  {{substr($f->description,0,20)}}... <button class="text-red-400" id="myBtn{{$f->id}}" onclick="myFunction({{$f->id}})">read more</button>
                    <p  class="block text-justify mx-4 max-w-[230px]" style="display:none" id="more{{$f->id}}"> 
                    {{$f->description}} <button class="text-red-400" id="myBtn{{$f->id}}" onclick="myFunction({{$f->id}})">read less</button>
                    </p>
                </div>

            @endforeach
         
        </div>
    </div>
</div>
<div class="flex justify-center items-center p-3">
    {{ $files->links() }}</div>
    
@include('layouts.footer')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $("#query").load("allDocuments.blade.php");
    });
</script>
<script>
    function myFunction(id) {
      var dots = document.getElementById("dots"+id);
      var moreText = document.getElementById("more"+id);
      var btnText = document.getElementById("myBtn"+id);
    
      if (dots.style.display === "none") {
        dots.style.display = "inline";
        btnText.innerHTML = "read more"; 
        moreText.style.display = "none";
      } else {
        dots.style.display = "none";
        btnText.innerHTML = "read less"; 
        moreText.style.display = "block";
      }
    }
    </script>
