@include('layouts.app')

<div class="grid sm:grid-cols-3 grid-cols-1 gap-3 bg-[#d8b64b] sm:h-64 lg:h-48 content-center">
    <div class="flex justify-center">
        <img class="w-36 " src="{{asset('storyset/Hiring-amico.png')}}" alt="" >
    </div>
   
    <div > <h1 class=" text-6xl text-white text-center mt-4">Juristify</h1>
        <p class=" text-2xl text-white text-center">Information</p>
    </div>
    <div class="flex justify-center">        
  <a data-popover-target="popover-description" class="flex items-center text-sm font-light text-white  dark:text-white">What can I find here click me <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="ml-2 w-4 h-4 text-white hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button></a>
  <div data-popover="" id="popover-description" role="tooltip" class="inline-block absolute invisible z-10 w-72 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm opacity-0 transition-opacity duration-300 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 410.4px, 0px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
    <div class="p-3 space-y-2">
        <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
        <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
        <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
        <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
    </div>
    <div data-popper-arrow="" style="position: absolute; left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
  </div>
  
    </div>
  </div>
<div class="w-full  shadow p-20 rounded-lg bg-white">
    <div class="relative">
        <div class="absolute flex items-center ml-2 h-full">
            <svg class="w-4 h-4 fill-current text-primary-gray-dark" viewBox="0 0 16 16" fill="none"
                xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M15.8898 15.0493L11.8588 11.0182C11.7869 10.9463 11.6932 10.9088 11.5932 10.9088H11.2713C12.3431 9.74952 12.9994 8.20272 12.9994 6.49968C12.9994 2.90923 10.0901 0 6.49968 0C2.90923 0 0 2.90923 0 6.49968C0 10.0901 2.90923 12.9994 6.49968 12.9994C8.20272 12.9994 9.74952 12.3431 10.9088 11.2744V11.5932C10.9088 11.6932 10.9495 11.7869 11.0182 11.8588L15.0493 15.8898C15.1961 16.0367 15.4336 16.0367 15.5805 15.8898L15.8898 15.5805C16.0367 15.4336 16.0367 15.1961 15.8898 15.0493ZM6.49968 11.9994C3.45921 11.9994 0.999951 9.54016 0.999951 6.49968C0.999951 3.45921 3.45921 0.999951 6.49968 0.999951C9.54016 0.999951 11.9994 3.45921 11.9994 6.49968C11.9994 9.54016 9.54016 11.9994 6.49968 11.9994Z">
                </path>
            </svg>
        </div>

        <input type="text" placeholder="Search by listing, location, bedroom number..."
            class="px-8 py-3 w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 text-sm">
    </div>

    <div class="flex items-center justify-between mt-4">
        <p class="font-medium">
            Filters
        </p>

        <button class="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-800 text-sm font-medium rounded-md">
            Reset Filter
        </button>
    </div>

    <div>
        <div class="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4 mt-4">
            <select
                class="px-4 py-3 w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 text-sm">
                <option value="">All Type</option>
                <option value="for-rent">For Rent</option>
                <option value="for-sale">For Sale</option>
            </select>

            <select
                class="px-4 py-3 w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 text-sm">
                <option value="">Furnish Type</option>
                <option value="fully-furnished">Fully Furnished</option>
                <option value="partially-furnished">Partially Furnished</option>
                <option value="not-furnished">Not Furnished</option>
            </select>

            <select
                class="px-4 py-3 w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 text-sm">
                <option value="">Any Price</option>
                <option value="1000">RM 1000</option>
                <option value="2000">RM 2000</option>
                <option value="3000">RM 3000</option>
                <option value="4000">RM 4000</option>
            </select>

            <select
                class="px-4 py-3 w-full rounded-md bg-gray-100 border-transparent focus:border-gray-500 focus:bg-white focus:ring-0 text-sm">
                <option value="">Floor Area</option>
                <option value="200">200 sq.ft</option>
                <option value="400">400 sq.ft</option>
                <option value="600">600 sq.ft</option>
                <option value="800 sq.ft">800</option>
                <option value="1000 sq.ft">1000</option>
                <option value="1200 sq.ft">1200</option>
            </select>
        </div>
    </div>

    <div class="pt-6 pb-12 flex">
        <div id="card" class="md:w-3/4">
 @foreach ($infos as $i)
            <!-- container for all cards -->
            {{-- <div class="container w-100 md:w-4/5 mx-auto flex flex-col mb-4">
                <!-- card -->
               
                    @php
                        $link = explode('/', $i->img);
                        
                    @endphp



                    <a data-modal-toggle="defaultModal{{ $i->id }}"
                        class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row  hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
                        <img class="object-cover h-48 w-48 rounded-l"
                            src="{{ asset('storage/info/' . $link[2]) }}" alt="" width="200px" height="200px">
                        <div class="flex flex-col justify-between p-4 leading-normal w-full">
                            <div class="flex justify-between">
                                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                    {{ $i->titulli }}</h5>
                                <p class="justify-end bg-gray-200 rounded h-50 p-1"><i
                                        class="fa-solid fa-clock"></i>{{ ' ' . $i->dataSkadimit }} dite te mbetura</p>
                            </div>
                            <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                                {{ substr($i->pershkrimi, 0, 237) }}...</p>
                            <div class="flex justify-start">
                                <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                        class="fa-solid fa-briefcase"></i>{{ ' ' . $i->emriKompanis }}</p>
                                <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                        class="fa-solid fa-tag"></i>{{ ' ' . $i->kategoria }}</p>
                                <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                        class="fa-solid fa-location-dot"></i>{{ ' ' . $i->lokacioni }}</p>
                            </div>
                        </div>

                    </a>





                    <!-- Main modal -->
                    <div id="defaultModal{{ $i->id }}" tabindex="-1" aria-hidden="true"
                        class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full justify-center items-center">
                        <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
                            <!-- Modal content -->
                            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                                <!-- Modal header -->
                                <div
                                    class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                                        More Information
                                    </h3>
                                    <button type="button"
                                        class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white"
                                        data-modal-toggle="defaultModal{{ $i->id }}">
                                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd"
                                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                                clip-rule="evenodd"></path>
                                        </svg>
                                        <span class="sr-only">Close modal</span>
                                    </button>
                                </div>
                                <!-- Modal body -->
                                <div class="p-6 space-y-6">
                                    <div class="lg:flex justify-between">
                                        <div class="lg:flex justify-start">
                                            <img class="object-cover w-full h-72 rounded-t-lg md:h-auto md:w-36 md:rounded-none md:rounded-l-lg"
                                                src="{{ asset('storage/info/' . $link[2]) }}" alt="">
                                            <h1 class="font-bold text-2xl relative lg:top-10 ml-3">{{ $i->titulli }}</h1>
                                        </div>
                                        <div class="">
                                            <p class="lg:justify-end bg-gray-200 rounded p-1  "><i
                                                    class="fa-solid fa-clock"></i>{{ ' ' . $i->dataSkadimit }} dite te
                                                mbetura</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="flex justify-start ml-6">
                                    <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                            class="fa-solid fa-person-circle-plus"></i>{{ ' ' . $i->vende }} vende te
                                        lira</p>

                                    <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                            class="fa-solid fa-briefcase"></i>{{ ' ' . $i->emriKompanis }}</p>
                                    <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                            class="fa-solid fa-tag"></i>{{ ' ' . $i->kategoria }}</p>
                                    <p class="mr-5 bg-gray-200 rounded h-50 p-1"><i
                                            class="fa-solid fa-location-dot"></i>{{ ' ' . $i->lokacioni }}</p>
                                </div>
                                <p class="font-bold text-base leading-relaxed ml-6 mt-3">{{ $i->titulli }}</p>
                                <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400 p-4">
                                    {{ $i->pershkrimi }}</p>

                                    <h1 class="p-4">
                                      <button type="button" data-modal-toggle="defaultModal{{ $i->id }}" class="w-full inline-block   p-3 bg-yellow-500 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-yellow-600 hover:shadow-lg focus:bg-yellow-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-700 active:shadow-lg transition duration-150 ease-in-out">Back to information</button>

                                    </h1>

                            </div>
                            
                            <!-- Modal footer -->

                        </div>
                    </div>
            </div> --}}
            @php
            $link = explode('/', $i->img);
            
        @endphp
            <div class="container mx-auto px-20 mb-3">
                <div class="flex bg-white border border-gray-500 rounded-xl overflow-hidden items-center justify-start" style="cursor: auto;">
                                            
                  <div class="relative w-32 h-32 flex-shrink-0">
                                                
                    <div class="absolute left-0 top-0 w-full h-full flex items-center justify-center">
                                                    
                      <img alt="Placeholder Photo" class="absolute left-0 top-0 w-full h-full object-cover object-center transition duration-50" loading="lazy" src="{{ asset('storage/info/' . $link[2]) }}">
                                                
                    </div>
                                            
                  </div>
                                            
                  <div class="p-4">
                                                
                    <p class="text-sm line-clamp-1 font-bold">{{$i->titulli}}</p>
                                                
                    <p class="text-sm text-gray-500 mt-1 line-clamp-2"> {{ substr($i->pershkrimi, 0, 237) }}...</p>
                                                
                    <span class="flex items-center justify-start text-gray-500 mt-3">
                                                    
                        <i class="fa-solid fa-briefcase mr-1"></i>{{' ' . $i->emriKompanis }}
                        <i class="fa-solid fa-tag mr-1 ml-5"></i>{{ ' ' . $i->kategoria }}
                                                
                    </span>
                                            
                  </div>
                                        
                </div>
                </div>
            @endforeach
            <!--/ card-->
        </div>
        <!--/ flex-->
    </div>
    <div>

    </div>
</div>
</div>


@include('layouts.footer')
