
@include('layouts.app')

<div class="grid sm:grid-cols-3 grid-cols-1 gap-3 bg-[#d8b64b] sm:h-64 lg:h-48 content-center">
  <div class="flex justify-center">
      <img class="w-36 " src="{{asset('storyset/News-amico.png')}}" alt="" >
  </div>
 
  <div > <h1 class=" text-6xl text-white text-center mt-4">Juristify</h1>
      <p class=" text-2xl text-white text-center">News</p>
  </div>
  <div class="flex justify-center">        
<a data-popover-target="popover-description" class="flex items-center text-sm font-light text-white  dark:text-white">What can I find here click me <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="ml-2 w-4 h-4 text-white hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button></a>
<div data-popover="" id="popover-description" role="tooltip" class="inline-block absolute invisible z-10 w-72 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm opacity-0 transition-opacity duration-300 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 410.4px, 0px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
  <div class="p-3 space-y-2">
      <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
      <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
      <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
      <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
  </div>
  <div data-popper-arrow="" style="position: absolute; left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
</div>

  </div>
</div>
<section class="text-gray-600 body-font">
    <div class="container lg:px-5 pb-24 mt-4 mx-auto max-w-7x1">
    
      <div class="flex flex-wrap -m-4">
    
        @foreach ($news as $n)
        @php
        $link = explode('/', $n->img);
        
    @endphp

        <div class="xl:w-1/3 md:w-1/2 p-4"> 
           <a href="{{route('news.show',$n->id)}}/?{{$n->titulli}}">
          <div class="bg-white p-6 rounded-lg">
            <img class="lg:h-60 xl:h-56 md:h-64 sm:h-72 xs:h-72 h-72  rounded w-full object-cover object-center mb-6" src="{{ asset('storage/news/' . $link[2]) }}" alt="Image Size 720x400">
            <h3 class="tracking-widest text-[#d8b64b] text-xs font-medium title-font ">{{$n->kategoria}} / {{date('d F, Y', strtotime($n->created_at))}}</h3>
            <h2 class="text-lg text-gray-900 font-medium title-font mb-4"> @if (strlen($n->titulli)>=37)
              {{substr($n->titulli,0,37)}}... 
              @else
              {{$n->titulli}}
              @endif</h2>
            <p class="leading-relaxed text-base"> {{ substr($n->pershkrimi, 0, 240) }}...</p>
          </div></a>
        </div>
          @endforeach
  
       
       
      </div>
      <div class="flex justify-center items-center p-3">
      {{$news->links()}}
    </div>
    </div>
  </section>


  @include('layouts.footer')