
@include('layouts.app')
<div class="grid sm:grid-cols-3 grid-cols-1 gap-3 bg-[#d8b64b] sm:h-64 lg:h-48 content-center">
  <div class="flex justify-center">
      <img class="w-36 " src="{{asset('storyset/News-amico.png')}}" alt="" >
  </div>
 
  <div > <h1 class=" text-6xl text-white text-center mt-4">Juristify</h1>
      <p class=" text-2xl text-white text-center">News</p>
  </div>
  <div class="flex justify-center">        
<div data-popover="" id="popover-description" role="tooltip" class="inline-block absolute invisible z-10 w-72 text-sm font-light text-gray-500 bg-white rounded-lg border border-gray-200 shadow-sm opacity-0 transition-opacity duration-300 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 410.4px, 0px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
  <div class="p-3 space-y-2">
      <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
      <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
      <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
      <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
  </div>
  <div data-popper-arrow="" style="position: absolute; left: 0px; transform: translate3d(0px, 0px, 0px);"></div>
</div>

  </div>
</div>
<section class="text-gray-600 body-font">
    <div class="container lg:px-5 pb-24 mt-4 mx-auto max-w-7x1">
        <div class="m-2.5 w-full flex justify-center">
          <form  action="{{ route('news.find') }}" method="GET" role="search">
            <div class="max-w-xl">
              {{-- <div class="flex space-x-1 items-center mb-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-[#d8b64b]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <p class="text-[#d8b64b] text-lg font-semibold">Search about title</p>
              </div> --}}
              <div class="flex space-x-4">
                <div class="flex rounded-md overflow-hidden w-full">
                  <input type="text" name="term" class="w-full rounded-md rounded-r-none" />
                  <a href="{{route('news.find')}}" >
                  <button class="bg-[#374151] text-white px-6 text-lg font-semibold py-4 rounded-r-md">Search</button>
                  </a>
                </div>
               
              </div>
            </div>
          </form>
           <a href={{route('news.view')}}>
                <button class="bg-transparent px-6 text-lg font-semibold py-4 rounded-md">Clear</button></a>
        </div>
        {{-- @if (count($news)>=1) --}}
          
       
      <div class="flex flex-wrap">
    
        @foreach ($news as $n)
        @php
        $link = explode('/', $n->img);
        
    @endphp

        <div class="xl:w-1/3 md:w-1/2 p-4"> 
           <a href="{{route('news.show',$n->id)}}/?{{$n->title}}">
          <div class="bg-white p-6 rounded-lg shadow-xl">
            <img class="lg:h-60 xl:h-56 md:h-64 sm:h-72 xs:h-72 h-72  rounded w-full  object-contain object-center mb-6" src="{{ asset('storage/news/' . $link[2]) }}" alt="Image Size 720x400">
            <h3 class="tracking-widest text-[#d8b64b] text-xs font-medium title-font ">{{$n->category}} / {{date('d F, Y', strtotime($n->created_at))}}</h3>
            <h2 class="text-lg text-gray-900 font-medium title-font mb-4"> @if (strlen($n->title)>=37)
              {{substr($n->title,0,37)}}... 
              @else
              {{$n->title}}
              @endif</h2>
            <p class="leading-relaxed text-base"> {{ substr($n->description, 0, 45) }}...</p>
          </div></a>
        </div>
          @endforeach
  
       
       
      </div>
      <div class="flex justify-center items-center p-3">
        {{$news->links()}}
    </div>
    {{-- @else
    <div class="grid place-items-center mt-10">
      <div class="flex items-center p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
          <svg aria-hidden="true" class="flex-shrink-0 inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Info</span>
          <div>
            <span class="font-medium">Info alert!</span> Change a few things up and try submitting again.
          </div>
        </div></div>
    @endif --}}
    </div>
  </section>


  @include('layouts.footer')